{
    'name': 'Customer Management',
    'version': '18.0.1.0.0',
    'summary': 'Quản lý hồ sơ và chăm sóc khách hàng',
    'category': 'Sales/CRM',
    'depends': ['base', 'contacts', 'mail'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/customer_views.xml',
        'views/care_need_views.xml',
        'views/skin_profile_views.xml',
        'views/treatment_views.xml',
        'views/customer_loyalty_views.xml',
        'views/customer_menu.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
